##
# libFreeBSD Makefile
##

TARGET_BASE:=		FreeBSD

# Uncomment to compile in debug mode.
#DEBUG:=			true

JNI_LINUX_LINK:= 	-lLCJNI -lX11

JAVAH_CLASSES:=	com.lightcrafts.platform.freebsd.FreeBSDKeyUtil

ROOT:=		../../..
include		../jni-freebsd.mk

# vim:set noet sw=8 ts=8:
