/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lightcrafts_platform_freebsd_FreeBSDKeyUtil */

#ifndef _Included_com_lightcrafts_platform_freebsd_FreeBSDKeyUtil
#define _Included_com_lightcrafts_platform_freebsd_FreeBSDKeyUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lightcrafts_platform_freebsd_FreeBSDKeyUtil
 * Method:    isKeyPressed
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_lightcrafts_platform_freebsd_FreeBSDKeyUtil_isKeyPressed
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
